### ISSUE TITLE
Add Navigation Buttons for Growth Meter, Planner, and Tracker

### ISSUE THREAD

**Issue by vivek-bandi** [Leadlly/leadlly.in#15]
I’m aiming to improve navigation within the application, as users currently find it difficult to access the Growth Meter, Planner Details, and Tracker features.

I propose adding buttons on the homepage that link directly to these sections, allowing users to navigate to specific routes like /growth-meter easily.

Implementing this will help contributors navigate the site more easily, reduce confusion, and address the remaining issues effectively.

**Comment by shivang-16** [comment]
we don't need this
